# Generated by Django 4.2.1 on 2023-07-30 21:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['-shared_at']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='post',
            field=models.ForeignKey(
                 on_delete=django.db.models.deletion.CASCADE, related_name='files', to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='shared_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
