# Generated by Django 4.2.1 on 2023-08-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_share_options_remove_post_files_file_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(blank=True, to='posts.file'),
        ),
    ]
