# Generated by Django 4.2.1 on 2023-07-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='post_media/'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
