# Generated by Django 4.2.1 on 2023-07-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='categories',
            new_name='category',
        ),
    ]
