# Generated by Django 4.2.1 on 2023-07-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='published_by',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='categories',
            field=models.CharField(choices=[('politics', 'Politics'), ('sport', 'Sport'), ('entertainment', 'Entertainment'), ('metro', 'Metro'), ('more', 'More')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediafile',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
