# Generated by Django 4.2.1 on 2023-07-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_mediafile_options_alter_mediafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='article_files/'),
        ),
    ]
