# Generated by Django 4.2.1 on 2023-07-22 03:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_file_remove_mediafile_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
