# Generated by Django 4.2.1 on 2023-07-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_mediafile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='files',
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.FileField(blank=True, upload_to='article_media/'),
        ),
    ]
