# Generated by Django 4.2.1 on 2023-07-23 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupinvitation',
            options={'ordering': ['-invited_at']},
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invited_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
