# Generated by Django 3.2.7 on 2023-10-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationgroup',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversationgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
