# Generated by Django 4.2.1 on 2023-07-04 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth import get_user_model
User = get_user_model()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_groups', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='conversationgroup',
            name='creator',
            field=models.ForeignKey(default=get_user_model().objects.first(
            ).pk, on_delete=django.db.models.deletion.CASCADE, related_name='groupcreator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        )
    ]
