# Generated by Django 4.2.1 on 2023-08-10 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationgroup',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversationgroup',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='conversationgroup',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='conversationgroup',
            name='admin_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversationgroup',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group/avatars/'),
        ),
        migrations.AlterField(
            model_name='conversationgroup',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='group/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='conversationgroup',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversationgroup',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='usergroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversationgroup',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
