# Generated by Django 4.2.1 on 2023-07-06 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_groups', '0002_conversationgroup_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='group/media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='user_groups.conversationgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='conversationtopic',
            name='group',
        ),
        migrations.RemoveField(
            model_name='conversationtopic',
            name='starter',
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
        migrations.DeleteModel(
            name='ConversationTopic',
        ),
    ]
