# Generated by Django 4.2.1 on 2023-08-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0002_alter_groupchat_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationgroup',
            old_name='creator',
            new_name='admin',
        ),
    ]
