# Generated by Django 4.2.1 on 2023-08-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0002_alter_conversationgroup_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppost',
            old_name='media',
            new_name='files',
        ),
    ]
