# Generated by Django 4.2.1 on 2023-05-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('COMPLICATED', 'Complicated'), ("I'D RATHER NOT SAY", "I'd Rather Not Say")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=123456789, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
