# Generated by Django 4.2.1 on 2023-05-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
