# Generated by Django 4.2.1 on 2023-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
