# Generated by Django 4.2.1 on 2023-07-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='is_online',
        ),
    ]
