# Generated by Django 4.2.1 on 2023-06-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_reset_password_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_image_path'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_image_path'),
        ),
    ]
