# Generated by Django 4.2.1 on 2023-08-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_avatar_alter_user_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('accept_friend_request', 'Accept Friend Request'), ('group_request', 'Group Request'), ('post_comment', 'Post Comment'), ('post_like', 'Post Like'), ('post_share', 'Post Share')], default='friend_request', max_length=30),
        ),
    ]
