# Generated by Django 4.2.1 on 2023-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('accept_friend_request', 'Accept Friend Request'), ('group_request', 'Group Request'), ('group_request_accept', 'Accept Group Request'), ('post_comment', 'Post Comment'), ('post_like', 'Post Like'), ('post_share', 'Post Share')], default='friend_request', max_length=30),
        ),
    ]
