# Generated by Django 4.2.1 on 2023-08-22 09:42

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0007_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(default=accounts.models.FriendRequest, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.UUIDField(default='153c93e1-14ef-4460-a098-d1e38c6d5f82'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('accept_friend_request', 'Accept Friend Request'), ('group_request', 'Group Request'), ('group_request_accept', 'Accept Group Request'), ('post_comment', 'Post Comment'), ('post_like', 'Post Like'), ('post_share', 'Post Share')], default='friend_request', max_length=30),
        ),
    ]
