# Generated by Django 4.2.1 on 2023-06-23 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_friendship_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('admin_phone', models.CharField(max_length=20)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_website', models.URLField()),
                ('background_image', models.ImageField(upload_to='group/backgrounds/')),
                ('avatar', models.ImageField(upload_to='group/avatars/')),
                ('members', models.ManyToManyField(related_name='usergroups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.conversationgroup')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
