# Generated by Django 4.2.1 on 2023-07-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvitation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConversationGroup',
        ),
        migrations.DeleteModel(
            name='GroupInvitation',
        ),
    ]
