# Generated by Django 4.2.1 on 2023-08-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('politics', 'Politics'), ('sport', 'Sport'), ('entertainment', 'Entertainment'), ('metro', 'Metro'), ('more', 'More'), ('education', 'EDUCATION'), ('gossip', 'GOSSIP')], max_length=20),
        ),
    ]
