# Generated by Django 3.2.7 on 2023-10-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='status',
            field=models.CharField(default='unread', max_length=15),
            preserve_default=False,
        ),
    ]
